http_port 80
pid_filename /tmp/squid.pid

# Allowed destinations
{{DOMAIN_ACLS}}

# HTTPS (CONNECT) and HTTP access control
acl SSL_ports port 443
acl CONNECT method CONNECT

http_access allow CONNECT SSL_ports allowed_domains
http_access allow allowed_domains
http_access deny all

# Logging
access_log stdio:/dev/stderr
cache_log stdio:/dev/stderr

# No caching
cache deny all
