use std::io::Write;
use std::path::Path;

const DEVCONTAINER_JSON_TEMPLATE: &str = include_str!("templates/devcontainer.json");
const DEVCONTAINER_COMPOSE_TEMPLATE: &str = include_str!("templates/compose-devcontainer.yaml");

/// Extension installed into every generated dev container.
const DEFAULT_EXTENSION: &str = "anthropic.claude-code";

/// Name of the compose override written next to the generated `compose.yaml`.
const COMPOSE_OVERRIDE_FILE: &str = "compose.devcontainer.yaml";

/// Marker comment on the first line of every `devcontainer.json` we generate.
/// `devcontainer.json` is JSONC, so the comment is legal; its presence is what
/// tells us the file is ours to overwrite (and ours to delete on `clean`).
pub const GENERATED_MARKER: &str = "// Generated by claude-container";

/// Escape a string for embedding in a JSON string literal.
fn escape_json(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out
}

/// Render the VS Code extension list: the default extension plus any extras,
/// one per line, as a comma-separated JSON array body.
///
/// Blank extras are dropped and duplicates are removed case-insensitively,
/// since VS Code extension ids are not case-sensitive.
fn format_extensions(extras: &[String]) -> String {
    let mut ids: Vec<&str> = vec![DEFAULT_EXTENSION];
    let mut seen: Vec<String> = vec![DEFAULT_EXTENSION.to_lowercase()];
    for e in extras {
        let id = e.trim();
        if id.is_empty() {
            continue;
        }
        let key = id.to_lowercase();
        if seen.contains(&key) {
            continue;
        }
        seen.push(key);
        ids.push(id);
    }
    ids.iter()
        .map(|id| format!("        \"{}\"", escape_json(id)))
        .collect::<Vec<_>>()
        .join(",\n")
}

/// Generate the contents of `.devcontainer/devcontainer.json`.
///
/// `compose_ref` is the directory holding the generated compose files, written
/// as VS Code resolves it: relative to the `.devcontainer/` directory itself.
fn generate_devcontainer_json(compose_ref: &str, extensions: &[String]) -> String {
    DEVCONTAINER_JSON_TEMPLATE
        .replace("{{COMPOSE_DIR}}", compose_ref)
        .replace("{{EXTENSIONS}}", &format_extensions(extensions))
}

/// Write the Dev Containers setup: a compose override that idles the claude
/// service, plus the `devcontainer.json` VS Code discovers at the project root.
///
/// `dir` is the project root; `compose_dir` is the generated `.claude-container`
/// directory inside it.
pub fn write_devcontainer(
    dir: &Path,
    compose_dir: &Path,
    extensions: &[String],
) -> Result<(), String> {
    // `.devcontainer/` and the compose directory are siblings under the project
    // root, so the paths VS Code resolves are `../<compose dir>/...`.
    let compose_ref = compose_dir
        .file_name()
        .map(|name| format!("../{}", name.to_string_lossy()))
        .ok_or_else(|| {
            format!(
                "Cannot reference compose directory '{}' from .devcontainer/",
                compose_dir.display()
            )
        })?;

    let devcontainer_dir = dir.join(".devcontainer");
    let json_path = devcontainer_dir.join("devcontainer.json");

    // Never clobber a devcontainer.json we did not write.
    if let Ok(existing) = std::fs::read_to_string(&json_path) {
        if !existing.contains(GENERATED_MARKER) {
            return Err(format!(
                "Found an existing {} that was not generated by claude-container; \
                 refusing to overwrite it.\nRemove or move it first, then re-run \
                 `claude-container build ... --devcontainer`.",
                json_path.display()
            ));
        }
    }

    let override_path = compose_dir.join(COMPOSE_OVERRIDE_FILE);
    let mut f = std::fs::File::create(&override_path)
        .map_err(|e| format!("Failed to write {COMPOSE_OVERRIDE_FILE}: {e}"))?;
    f.write_all(DEVCONTAINER_COMPOSE_TEMPLATE.as_bytes())
        .map_err(|e| format!("Failed to write {COMPOSE_OVERRIDE_FILE}: {e}"))?;
    eprintln!("Wrote {}", override_path.display());

    std::fs::create_dir_all(&devcontainer_dir)
        .map_err(|e| format!("Failed to create .devcontainer directory: {e}"))?;

    let mut f = std::fs::File::create(&json_path)
        .map_err(|e| format!("Failed to write devcontainer.json: {e}"))?;
    f.write_all(generate_devcontainer_json(&compose_ref, extensions).as_bytes())
        .map_err(|e| format!("Failed to write devcontainer.json: {e}"))?;
    eprintln!("Wrote {}", json_path.display());

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    const ENTRYPOINT_SCRIPT: &str = include_str!("templates/entrypoint.sh");
    const COMPOSE_REF: &str = "../.claude-container";

    fn render(extensions: &[String]) -> String {
        generate_devcontainer_json(COMPOSE_REF, extensions)
    }

    #[test]
    fn test_template_carries_the_generated_marker() {
        assert!(DEVCONTAINER_JSON_TEMPLATE.starts_with(GENERATED_MARKER));
        assert!(render(&[]).contains(GENERATED_MARKER));
    }

    #[test]
    fn test_devcontainer_json_structure() {
        let json = render(&[]);
        assert!(json.contains("\"name\": \"claude-container\""));
        assert!(json.contains("\"service\": \"claude\""));
        assert!(json.contains("\"workspaceFolder\": \"/workarea\""));
        assert!(json.contains("\"overrideCommand\": false"));
        // The marker comment precedes the object; the body is still an object.
        let body = json
            .split_once('\n')
            .expect("marker comment is its own line")
            .1;
        assert!(body.starts_with('{'));
        assert!(body.trim_end().ends_with('}'));
    }

    #[test]
    fn test_devcontainer_json_references_both_compose_files() {
        let json = render(&[]);
        assert!(json.contains("\"../.claude-container/compose.yaml\""));
        assert!(json.contains("\"../.claude-container/compose.devcontainer.yaml\""));
    }

    #[test]
    fn test_compose_dir_placeholder_is_substituted() {
        let json = generate_devcontainer_json("../custom-dir", &[]);
        assert!(json.contains("\"../custom-dir/compose.yaml\""));
        assert!(json.contains("\"../custom-dir/compose.devcontainer.yaml\""));
        assert!(!json.contains("{{COMPOSE_DIR}}"));
    }

    #[test]
    fn test_default_extension_always_present() {
        let json = render(&[]);
        assert!(json.contains("\"anthropic.claude-code\""));
        // No extras: the array body is a single entry with no trailing comma.
        assert!(json.contains("\"extensions\": [\n        \"anthropic.claude-code\"\n      ]"));
    }

    #[test]
    fn test_single_extra_extension() {
        let json = render(&["ms-python.python".to_string()]);
        assert!(json.contains(
            "\"extensions\": [\n        \"anthropic.claude-code\",\n        \"ms-python.python\"\n      ]"
        ));
    }

    #[test]
    fn test_multiple_extra_extensions() {
        let json = render(&[
            "ms-python.python".to_string(),
            "rust-lang.rust-analyzer".to_string(),
        ]);
        assert!(json.contains(
            "\"extensions\": [\n        \"anthropic.claude-code\",\n        \"ms-python.python\",\n        \"rust-lang.rust-analyzer\"\n      ]"
        ));
        assert_eq!(json.matches("        \"").count(), 3);
    }

    #[test]
    fn test_default_extension_is_not_duplicated() {
        let json = render(&["anthropic.claude-code".to_string()]);
        assert_eq!(json.matches("\"anthropic.claude-code\"").count(), 1);
    }

    #[test]
    fn test_default_extension_is_not_duplicated_case_insensitively() {
        let body = format_extensions(&["Anthropic.Claude-Code".to_string()]);
        assert_eq!(body, "        \"anthropic.claude-code\"");
    }

    #[test]
    fn test_extras_are_deduped_case_insensitively() {
        let body = format_extensions(&[
            "ms-python.python".to_string(),
            "MS-Python.Python".to_string(),
            "rust-lang.rust-analyzer".to_string(),
        ]);
        // The first spelling wins; the later casing variant is dropped.
        assert_eq!(
            body,
            "        \"anthropic.claude-code\",\n        \"ms-python.python\",\n        \"rust-lang.rust-analyzer\""
        );
    }

    #[test]
    fn test_blank_extensions_are_skipped() {
        let body = format_extensions(&[
            String::new(),
            "   ".to_string(),
            "\t\n".to_string(),
            "ms-python.python".to_string(),
        ]);
        assert_eq!(
            body,
            "        \"anthropic.claude-code\",\n        \"ms-python.python\""
        );
    }

    #[test]
    fn test_extension_ids_are_trimmed() {
        let body = format_extensions(&["  ms-python.python  ".to_string()]);
        assert!(body.ends_with("\"ms-python.python\""));
    }

    #[test]
    fn test_extension_ids_are_escaped() {
        let body = format_extensions(&["we\"ird\\id".to_string()]);
        assert!(body.contains("\"we\\\"ird\\\\id\""));
    }

    #[test]
    fn test_compose_override_idles_the_claude_service() {
        assert!(DEVCONTAINER_COMPOSE_TEMPLATE.contains("claude:"));
        assert!(DEVCONTAINER_COMPOSE_TEMPLATE.contains("command: [\"devcontainer-idle\"]"));
    }

    #[test]
    fn test_entrypoint_has_idle_sentinel_branch() {
        assert!(ENTRYPOINT_SCRIPT.contains("\"$1\" = \"devcontainer-idle\""));
        assert!(ENTRYPOINT_SCRIPT.contains("while :; do sleep 3600; done"));
        assert!(ENTRYPOINT_SCRIPT.contains("exec claude \"$@\""));
    }

    #[test]
    fn test_entrypoint_idle_loop_is_portable() {
        // `sleep infinity` is a GNU coreutils extension; busybox `sleep` rejects it.
        assert!(!ENTRYPOINT_SCRIPT.contains("sleep infinity"));
    }

    #[test]
    fn test_existing_foreign_devcontainer_json_is_not_overwritten() {
        let dir = std::env::temp_dir().join(format!("cc-devcontainer-test-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        let compose_dir = dir.join(".claude-container");
        std::fs::create_dir_all(&compose_dir).unwrap();
        std::fs::create_dir_all(dir.join(".devcontainer")).unwrap();

        let json_path = dir.join(".devcontainer").join("devcontainer.json");
        std::fs::write(&json_path, "{ \"name\": \"mine\" }\n").unwrap();

        let err = write_devcontainer(&dir, &compose_dir, &[]).unwrap_err();
        assert!(err.contains("refusing to overwrite"));
        // Untouched, and no override file written either.
        assert_eq!(
            std::fs::read_to_string(&json_path).unwrap(),
            "{ \"name\": \"mine\" }\n"
        );
        assert!(!compose_dir.join(COMPOSE_OVERRIDE_FILE).exists());

        // A file bearing our marker is replaced without complaint.
        std::fs::write(&json_path, format!("{GENERATED_MARKER} stale\n{{}}\n")).unwrap();
        write_devcontainer(&dir, &compose_dir, &[]).unwrap();
        let written = std::fs::read_to_string(&json_path).unwrap();
        assert!(written.contains("\"service\": \"claude\""));
        assert!(compose_dir.join(COMPOSE_OVERRIDE_FILE).exists());

        let _ = std::fs::remove_dir_all(&dir);
    }
}
