use std::process::Command;

use crate::compose;
use crate::devcontainer;
use crate::persist;
use crate::runtime::Runtime;

/// Get the host user's UID and GID.
fn host_uid_gid() -> (u32, u32) {
    // SAFETY: getuid/getgid are always safe to call
    unsafe { (libc::getuid(), libc::getgid()) }
}

/// Resolve the host's HOME and the project directory being containerized.
fn host_home_and_workdir() -> Result<(String, String), String> {
    let home =
        std::env::var("HOME").map_err(|_| "HOME environment variable not set".to_string())?;
    let cwd =
        std::env::current_dir().map_err(|e| format!("Failed to get current directory: {e}"))?;
    let workdir = cwd
        .to_str()
        .ok_or("Current directory path is not valid UTF-8")?
        .to_string();
    Ok((home, workdir))
}

/// Collect the standard volume mounts as (host, container) pairs.
fn collect_mounts(
    home: &str,
    workdir: &str,
    forward_settings: bool,
    forward_git_config: bool,
    persist_state: bool,
) -> Result<Vec<(String, String)>, String> {
    let mut mounts = Vec::new();

    if forward_settings {
        let claude_dir = format!("{home}/.claude");
        if std::path::Path::new(&claude_dir).exists() {
            mounts.push((claude_dir, "/home/claude/.claude".to_string()));
        }

        let claude_json = format!("{home}/.claude.json");
        if std::path::Path::new(&claude_json).exists() {
            mounts.push((claude_json, "/home/claude/.claude.json".to_string()));
        }
    }

    if persist_state {
        mounts.extend(persist::persist_mounts(home, workdir, forward_settings)?);
    }

    if forward_git_config {
        let gitconfig = format!("{home}/.gitconfig");
        if std::path::Path::new(&gitconfig).exists() {
            mounts.push((gitconfig, "/home/claude/.gitconfig:ro".to_string()));
        }
    }

    mounts.push((workdir.to_string(), "/workarea".to_string()));
    Ok(mounts)
}

/// Build the .claude-container/ project directory (Dockerfile, compose.yaml, etc.)
#[allow(clippy::too_many_arguments)]
pub fn build(
    base_image: &str,
    profile: Option<&str>,
    isolated: bool,
    allow_hosts: &[String],
    forward_settings: bool,
    forward_git_config: bool,
    persist_state: bool,
    args: &[String],
    version: Option<&str>,
    devcontainer_enabled: bool,
    vscode_extensions: &[String],
) -> Result<(), String> {
    let (home, workdir) = host_home_and_workdir()?;
    let mounts = collect_mounts(
        &home,
        &workdir,
        forward_settings,
        forward_git_config,
        persist_state,
    )?;
    let (uid, gid) = host_uid_gid();

    // Persisted state is bind-mounted *inside* the /home/claude tmpfs. Give
    // ~/.claude its own user-owned tmpfs so the surrounding directory stays
    // writable — otherwise the runtime creates it root-owned and Claude cannot
    // write its settings. With --forward-settings that path is already a bind
    // mount of the host's ~/.claude, so no tmpfs is needed (or allowed) there.
    let extra_tmpfs: Vec<String> = if persist_state && !forward_settings {
        vec![persist::CONTAINER_CLAUDE_DIR.to_string()]
    } else {
        Vec::new()
    };

    let compose_dir = std::path::Path::new(".claude-container");
    std::fs::create_dir_all(compose_dir)
        .map_err(|e| format!("Failed to create .claude-container directory: {e}"))?;

    // Write a CLAUDE.md so Claude knows to ignore this directory
    let _ = std::fs::write(
        compose_dir.join("CLAUDE.md"),
        "This directory is auto-generated by claude-container. Do not edit or read files here.\n",
    );

    // Ignore all generated files in git
    let _ = std::fs::write(compose_dir.join(".gitignore"), "*\n");

    if isolated {
        eprintln!("Starting network-isolated session...");
        compose::write_isolated_project(
            compose_dir,
            base_image,
            profile,
            allow_hosts,
            &mounts,
            &extra_tmpfs,
            args,
            uid,
            gid,
            version,
        )?;
    } else {
        compose::write_simple_project(
            compose_dir,
            base_image,
            profile,
            &mounts,
            &extra_tmpfs,
            args,
            uid,
            gid,
            version,
        )?;
    };

    if devcontainer_enabled {
        if !args.is_empty() {
            eprintln!(
                "Warning: trailing arguments apply to `claude-container run` only — \
                 the dev container override replaces the container command, so they \
                 are ignored in dev container sessions."
            );
        }
        // The project root is the current directory; an empty path keeps the
        // printed paths relative (".devcontainer/devcontainer.json").
        let project_dir = std::path::Path::new("");
        devcontainer::write_devcontainer(
            project_dir,
            compose_dir,
            vscode_extensions,
            &home,
            &workdir,
        )?;
    }

    eprintln!("Built .claude-container/ project");
    Ok(())
}

/// Run a compose project, tearing down on exit.
fn run_compose(
    runtime: Runtime,
    compose_file: &std::path::Path,
    rebuild: bool,
) -> Result<(), String> {
    let compose_file_str = compose_file.to_str().ok_or("Non-UTF-8 path")?;
    let (cmd, base_args) = runtime.compose_cmd()?;

    let mut args: Vec<String> = base_args.clone();
    args.extend(["-f".to_string(), compose_file_str.to_string()]);
    args.extend([
        "run".to_string(),
        "--rm".to_string(),
        "--service-ports".to_string(),
    ]);
    if rebuild {
        args.push("--build".to_string());
    }
    args.push("claude".to_string());

    let status = Command::new(&cmd)
        .args(&args)
        .status()
        .map_err(|e| format!("Failed to run {cmd}: {e}"))?;

    // Always tear down on exit
    let mut down_args: Vec<String> = base_args;
    down_args.extend([
        "-f".to_string(),
        compose_file_str.to_string(),
        "down".to_string(),
    ]);
    let _ = Command::new(&cmd)
        .args(&down_args)
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status();

    if !status.success() {
        std::process::exit(status.code().unwrap_or(1));
    }

    Ok(())
}

/// Run the existing .claude-container/ compose project.
pub fn run(runtime: Runtime, rebuild: bool) -> Result<(), String> {
    let compose_file = std::path::Path::new(".claude-container/compose.yaml");
    if !compose_file.exists() {
        return Err(
            "No .claude-container/compose.yaml found. Build first with:\n  \
             claude-container build ubuntu:24.04"
                .to_string(),
        );
    }
    run_compose(runtime, compose_file, rebuild)
}
